[project]
name = "menthol-model"
version = "0.1.0"
description = "A microsimulation model for smoking behavior"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "debugpy>=1.8.20",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "scipy>=1.13.1",
]
